### ISSUE TITLE
Justify

### ISSUE THREAD

**Issue by Zsombe** [colorchestra/smol#32]
Hey!

Could you change the post text align to justify?

Thanks!

**Comment by contre95** [comment]
Just add `text-align: justify;` to the `article` class in the `themes/smigle/static/css/reset.css` file.

```css
article {
  padding: 5px 0;
  text-align: justify;
}
```
